/*
 * This source file was generated by the Gradle 'init' task
 */
package com.oop.Genesys;

import ui.Login;

public class App {
    public static void main(String[] args) {
        Login home = new Login();
        home.setVisible(true);
    }
}
